server:
  port: 8081 #Tomcat端口
spring:
  dubbo:    # Dubbo服务提供者配置
    application:
      name: dubbo-client  # 服务名称
    registry:
      address: zookeeper://127.0.0.1:2181  # 注册中心地址
    protocol:
      name: dubbo  # dubbo协议
      port: 28082  # dubbo协议端口